default:	cpsc2150/listDec/ShuffleApp.java cpsc2150/listDec/ShuffleList.java cpsc2150/listDec/IShuffleList.java

	javac cpsc2150/listDec/ShuffleApp.java cpsc2150/listDec/ShuffleList.java cpsc2150/listDec/IShuffleList.java

run:	cpsc2150/listDec/ShuffleApp.class cpsc2150/listDec/ShuffleList.class cpsc2150/listDec/IShuffleList.class

	java cpsc2150.listDec.ShuffleApp

clean:

	rm -f cpsc2150/listDec/*.class
