default: cpsc2150/MyVector/AbsVector.java cpsc2150/MyVector/ArrayVector.java cpsc2150/MyVector/CharacterVectorApp.java cpsc2150/MyVector/IVector.java cpsc2150/MyVector/ListVector.java
	javac -Xlint cpsc2150/MyVector/AbsVector.java cpsc2150/MyVector/ArrayVector.java cpsc2150/MyVector/CharacterVectorApp.java cpsc2150/MyVector/IVector.java cpsc2150/MyVector/ListVector.java

run: cpsc2150/MyVector/AbsVector.class cpsc2150/MyVector/ArrayVector.class cpsc2150/MyVector/CharacterVectorApp.class cpsc2150/MyVector/IVector.class cpsc2150/MyVector/ListVector.class
	java cpsc2150.MyVector.CharacterVectorApp

clean:
	rm -f cpsc2150/MyVector/*.class
