default:	cpsc2150/MyDeque/ArrayDeque.java cpsc2150/MyDeque/DequeApp.java cpsc2150/MyDeque/DoubleDequeApp.java cpsc2150/MyDeque/IDeque.java cpsc2150/MyDeque/ListDeque.java

	javac cpsc2150/MyDeque/ArrayDeque.java cpsc2150/MyDeque/DequeApp.java cpsc2150/MyDeque/DoubleDequeApp.java cpsc2150/MyDeque/IDeque.java cpsc2150/MyDeque/ListDeque.java

runInt:	cpsc2150/MyDeque/ArrayDeque.class cpsc2150/MyDeque/DequeApp.class cpsc2150/MyDeque/ListDeque.class

	java cpsc2150.MyDeque.DequeApp

runDouble:	cpsc2150/MyDeque/ArrayDeque.class cpsc2150/MyDeque/DoubleDequeApp.class cpsc2150/MyDeque/ListDeque.class

	java cpsc2150.MyDeque.DoubleDequeApp

clean:

	rm -f cpsc2150/MyDeque/*.class

